### ISSUE TITLE
关于napcat桌面版时不时与nb断连的问题

### ISSUE THREAD

**Issue by leopard-1** [NapNeko/NapCatQQ-Desktop#2]
**使用系统：windows 10 server 2022**
**RAM:2.00GB**
**NTQQ版本：9.9.12**
**napcat版本：1.6.6**
**CPU：志强2H（不知道是什么U 阿里云服务器）**
**框架/适配器:nonebot2+onebotV11**
**兼容模式：windows 8**
-------------------------------------------------------------------------------------------

不知道是什么原因 时不时与nb断连（回复失败？） 机器人数据量也不大，小的和我家里盒装的光明酸奶差不多（什么奇怪的形容）
我用的是反向连接nb  链接至ws://127.0.0.1:18080/onebot/v11/ws

（图一）napcat报错：
websocket 回复失败Error: WebSocket is
not open: readyState 0(CONNECTING).
at WebSocket.send(C:\Windows\system32\NapCat\node_modules\ws\lib\websocket.js:450:13)
at wsReply (file:///C:/Windows/system32/NapCat/napcat.mjs:18075:14)
at Timeout._onTimeout (file:///C:/Windows/system32/NapCat/napcat.mjs:30263:7)
at listOnTimeout (node:internal/timers:573:17)
at process.processTimers(node:internal/timers:514:7) {"time":1721138254,"self_id":
1658765967,"post_type":"meta event","meta event type":"heartbeat","status":
{"online":true, "good":true},"interval":""

（图二）nb报错:
nonebot. adapters. onebot. v11. exception.NetworkError: NetWorkError(message='WebSocket ca11 api get_group_member_info timeo
ut’)

----------------------------------------------------------------------------------------------

以下附图（请不要加bot好友谢谢）
如果需要提供更多信息请联系我

![0dc76ae6b84cd48855bca5c854a97151](https://github.com/user-attachments/assets/189c6d79-d92f-4945-be88-33d64d25bddc)
![4a25a0cef98182471d70631b50098e21](https://github.com/user-attachments/assets/0e2f8843-aa04-43c5-82f4-48e72979725b)

**Comment by leopard-1** [comment]
重启了一下 又出现了一个新问题

报错为：
[3244:0716/234628.053:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=18
[3244:0716/234628.053:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 5 time(s)
[3244:0716/234628.212:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=18
[3244:0716/234628.212:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 6 time(s)
[3244:0716/234628.355:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=18
[3244:0716/234628.360:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 7 time(s)
[3244:0716/234628.511:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=18
[3244:0716/234628.511:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 8 time(s)
[3244:0716/234628.664:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=18
[3244:0716/234628.664:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 9 time(s)
[3244:0716/234628.664:FATAL:gpu_data_manager_impl_private.cc(449)] GPU process isn't usable. Goodbye.

------------------------------------------------------------------------------
以下附图

![image](https://github.com/user-attachments/assets/ff92744d-ba65-4e24-86d8-0decb12a77c7)

**Comment by HeartfeltJoy** [comment]
报错的意思是WebSocket连接未打开

请附上以下内容以便于进行进一步排查:
1. NCD目录下的NapCat/config中你机器人的配置文件内容
2. NCD的版本号

**Comment by HeartfeltJoy** [comment]
issues中我回复可能会比较慢,建议添加NapCat的交流群寻求帮助 545402644

**Comment by leopard-1** [comment]
好的，非常感谢，交流群里见！

**Comment by xmexg** [comment]
> 好的，非常感谢，交流群里见！

你人呢？
![Screenshot_2024-07-18-10-11-25-896_com tencent mobileqq](https://github.com/user-attachments/assets/1385c426-17ec-4b2b-b136-3de3afda4655)
